export type MenuItem = {
  id: string;
  name: string;
  subtitle: string;
  category: "Starter" | "Curry" | "Biryani" | "Bread" | "South Indian" | "Drink" | "Dessert";
  veg: boolean;
  price: number;
  heat: 0 | 1 | 2 | 3 | 4 | 5;
  taste: string[];
  description: string;
  image: string;
};

export const menuItems: MenuItem[] = [
  {
    id: "samosa",
    name: "Samosa",
    subtitle: "Crisp, savory, warmly spiced",
    category: "Starter",
    veg: true,
    price: 7,
    heat: 2,
    taste: ["Crispy", "Savory", "Warm spice"],
    description: "Golden pastry filled with seasoned potato and peas, served hot with chutney.",
    image: "https://bharatjalpaan.ae/assets/images/samosa.png",
  },
  {
    id: "chicken-tikka",
    name: "Chicken Tikka",
    subtitle: "Smoky, charred, juicy",
    category: "Starter",
    veg: false,
    price: 14,
    heat: 3,
    taste: ["Smoky", "Savory", "Tangy"],
    description: "Yogurt-marinated chicken grilled until tender with caramelized, charred edges.",
    image: "https://static.wixstatic.com/media/6e28fb_57ea7b17375e47aa853a0253b3ccb01a~mv2.png/v1/fill/w_980,h_815,al_c,q_90,enc_avif,quality_auto/6e28fb_57ea7b17375e47aa853a0253b3ccb01a~mv2.png",
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    subtitle: "Creamy, buttery, gently sweet",
    category: "Curry",
    veg: false,
    price: 18,
    heat: 2,
    taste: ["Creamy", "Rich", "Mild"],
    description: "Tender chicken in a silky tomato-butter sauce with a mellow, comforting finish.",
    image: "https://b.zmtcdn.com/data/dish_photos/9bc/75f5a8ef577ac9f3b706f3701d9539bc.jpeg",
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    subtitle: "Earthy, creamy, comforting",
    category: "Curry",
    veg: true,
    price: 16,
    heat: 2,
    taste: ["Earthy", "Creamy", "Aromatic"],
    description: "Soft paneer cubes folded through a smooth spinach curry with fragrant spices.",
    image: "https://images.slurrp.com/prod/recipe_images/transcribe/main%20course/Palak-Paneer.webp?height=675&impolicy=slurrp-20210601&width=1200",
  },
  {
    id: "chicken-biryani",
    name: "Chicken Biryani",
    subtitle: "Fragrant, layered, bold",
    category: "Biryani",
    veg: false,
    price: 19,
    heat: 3,
    taste: ["Aromatic", "Savory", "Layered"],
    description: "Long-grain basmati rice layered with spiced chicken, herbs, saffron notes and fried onions.",
    image: "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/RX_THUMBNAIL/IMAGES/VENDOR/2024/11/14/98341df0-d993-4ad2-aef4-98a17b4cbcb2_990241.jpg",
  },
  {
    id: "vegetable-biryani",
    name: "Vegetable Biryani",
    subtitle: "Fragrant, colorful, aromatic",
    category: "Biryani",
    veg: true,
    price: 16,
    heat: 3,
    taste: ["Fragrant", "Savory", "Fresh"],
    description: "Basmati rice layered with vegetables, herbs, warm spices and crisp fried onions.",
    image: "https://tb-static.uber.com/prod/image-proc/processed_images/2cf3b8f2e83b2852c4d3b6f33328abcd/c67fc65e9b4e16a553eb7574fba090f1.jpeg",
  },
  {
    id: "garlic-naan",
    name: "Garlic Naan",
    subtitle: "Buttery, soft, lightly charred",
    category: "Bread",
    veg: true,
    price: 5,
    heat: 0,
    taste: ["Buttery", "Garlicky", "Toasty"],
    description: "Soft tandoor-baked flatbread brushed with butter, garlic and herbs.",
    image: "https://www.midamarhalal.com/cdn/shop/files/GarlicNaan_635d9283-15a8-4df2-9894-cd20bcaad918.jpg?v=1740159148",
  },
  {
    id: "masala-dosa",
    name: "Masala Dosa",
    subtitle: "Crispy, tangy, savory",
    category: "South Indian",
    veg: true,
    price: 13,
    heat: 2,
    taste: ["Crispy", "Tangy", "Savory"],
    description: "A thin crisp fermented crepe wrapped around seasoned potato, with chutney and sambar.",
    image: "https://www.kaufmann.wtf/countries/images/recipes/india-masala-dosa.jpg",
  },
  {
    id: "mango-lassi",
    name: "Mango Lassi",
    subtitle: "Creamy, fruity, cooling",
    category: "Drink",
    veg: true,
    price: 6,
    heat: 0,
    taste: ["Creamy", "Sweet", "Fruity"],
    description: "A chilled mango and yogurt drink with a smooth, refreshing finish.",
    image: "https://static.wixstatic.com/media/726cb8_bcfc2f50345e4f1a871b0e83d83dc3a8~mv2.jpg/v1/fill/w_980,h_1225,al_c,q_85,enc_avif,quality_auto/726cb8_bcfc2f50345e4f1a871b0e83d83dc3a8~mv2.jpg",
  },
  {
    id: "masala-chai",
    name: "Masala Chai",
    subtitle: "Warm, aromatic, cozy",
    category: "Drink",
    veg: true,
    price: 4,
    heat: 0,
    taste: ["Warm spice", "Milky", "Aromatic"],
    description: "Black tea simmered with milk and warming spices for a fragrant, comforting cup.",
    image: "https://chaiholic.in/images/chai.png",
  },
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    subtitle: "Soft, syrupy, floral",
    category: "Dessert",
    veg: true,
    price: 7,
    heat: 0,
    taste: ["Sweet", "Soft", "Floral"],
    description: "Warm milk-solid dumplings soaked in fragrant syrup, finished with pistachio.",
    image: "https://cf-img-a-in.tosshub.com/sites/visualstory/wp/2024/08/Gulab-Jamun.jpg?size=%2A%3A900",
  },
  {
    id: "rasmalai",
    name: "Rasmalai",
    subtitle: "Milky, delicate, saffron-kissed",
    category: "Dessert",
    veg: true,
    price: 8,
    heat: 0,
    taste: ["Creamy", "Sweet", "Delicate"],
    description: "Soft cheese dumplings in chilled sweetened milk with saffron and pistachio.",
    image: "https://www.bitesofindiarestaurant.uk/assets/images/generated/rasmalai.png",
  },
];

export const categories = ["All", "Starter", "Curry", "Biryani", "Bread", "South Indian", "Drink", "Dessert"] as const;
